### ISSUE TITLE
Models are not piece of Logic and should be treated as "Entities of Data" - EOD

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/sinatra-intro-to-mvc#8]
The idea is you keep business logic outside of the model.  Your model should have a Single Role Responsibility and be a well behaved data model.  This is becoming a defact-o standard in Rails so I highly suggest to not confuse learners and not talk about data models being logic.

Skinny Controllers - Don't put too much business logic into the controller!  Keep them skinny!  Complex pieces of logic are better abstracted as Services\Jobs\Concerns(pick your convention).  

This pattern is more maintainable and flexible.  If the business logic was to change you won't ruin your data models or controllers.

http://stackoverflow.com/questions/13951445/yes-or-no-should-models-in-mvc-contain-application-logic

I made up the phrase "Entities Of Data" to explain this concept.  An Entity of Data should be exactly that.  The data you manipulate and build logic around not in.

**Comment by PeterBell** [comment]
I think the curriculum does a reasonable job of explaining the components of MVC. This would actually be a great discussion to bring up as part of a study group, but I don't think there's really anything super wrong with the way this is being taught, so I'm going to close the issue (although do feel free to either reopen the issue or to submit a PR if there are specific actionable changes you'd like to see in the content).

Also, the idea of pulling business logic out of the model is pretty much a rails specific trend and due to the fact that Rails conflates persistence and business logic concerns (unless you do hexagonal rails or one of the other proposed patterns to avoid this issue). I general terms the model is absolutely where most of the business logic should go, and a common pattern in languages like Java is to use DAOs (Data Access Objects) retrived via Service Objects to handle the persistence concerns so your models can focus on business logic.
